[package]
name = "tuple-space-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tuple-space = {git = "ssh://misc.aimred.com/var/local/git/TupleSpace/tuple-space"}
